export type ChefCategory = 'michelin' | 'tv' | 'creator' | 'regional';

export interface Chef {
  id: string;
  name: string;
  title: string;
  nationality: string;
  category: ChefCategory;
  cuisine: string[];
  knownFor: string;
  philosophy: string;
  signatureDishes: string[];
  gradient: string;
  stars?: number;
  handle?: string;
}

export const CHEFS: Chef[] = [
  // ── MICHELIN ──────────────────────────────────────────────────────────────
  {
    id: 'gordon-ramsay',
    name: 'Gordon Ramsay',
    title: '7-Michelin-Star Chef',
    nationality: '🇬🇧 British',
    category: 'michelin',
    cuisine: ['British', 'French', 'Mediterranean'],
    knownFor: 'Beef Wellington, perfectly seared proteins, bold classical French technique with British influence. Founder of Restaurant Gordon Ramsay, Hell\'s Kitchen, and MasterChef.',
    philosophy: 'Perfection in simplicity. Every ingredient must earn its place on the plate. Classical technique executed flawlessly.',
    signatureDishes: ['Beef Wellington', 'Pan Seared Salmon', 'Sticky Toffee Pudding', 'Lobster Risotto'],
    gradient: 'from-red-600 to-orange-500',
    stars: 7,
  },
  {
    id: 'heston-blumenthal',
    name: 'Heston Blumenthal',
    title: '3-Michelin-Star Chef',
    nationality: '🇬🇧 British',
    category: 'michelin',
    cuisine: ['Molecular Gastronomy', 'British'],
    knownFor: 'The Fat Duck in Bray. Pioneer of molecular gastronomy. Famous for Triple Cooked Chips, Snail Porridge, Bacon & Egg Ice Cream, and multi-sensory dining experiences.',
    philosophy: 'Food is a multi-sensory experience. Science and creativity unlock flavors impossible with conventional cooking.',
    signatureDishes: ['Triple Cooked Chips', 'Perfect Steak', 'Bacon & Egg Ice Cream', 'Sound of the Sea'],
    gradient: 'from-violet-600 to-blue-500',
    stars: 3,
  },
  {
    id: 'massimo-bottura',
    name: 'Massimo Bottura',
    title: '3-Michelin-Star Chef',
    nationality: '🇮🇹 Italian',
    category: 'michelin',
    cuisine: ['Contemporary Italian', 'Emilian'],
    knownFor: 'Osteria Francescana in Modena, voted World\'s Best Restaurant. Famous for Five Ages of Parmigiano, Tagliatelle al Ragù, and dishes that reimagine Italian classics with avant-garde techniques.',
    philosophy: 'Italian tradition viewed through a contemporary lens. Every dish tells a cultural story.',
    signatureDishes: ['Tagliatelle al Ragù', 'Five Ages of Parmigiano', 'The Crunchy Part of the Lasagne', 'Oops I Dropped the Lemon Tart'],
    gradient: 'from-green-600 to-emerald-400',
    stars: 3,
  },
  {
    id: 'rene-redzepi',
    name: 'René Redzepi',
    title: '2-Michelin-Star Chef',
    nationality: '🇩🇰 Danish',
    category: 'michelin',
    cuisine: ['New Nordic', 'Foraging'],
    knownFor: 'Noma in Copenhagen, 4× World\'s Best Restaurant. Pioneered New Nordic cuisine using foraged ingredients, fermentation, and hyper-local produce.',
    philosophy: 'The forest, the sea, and the farm. Food rooted in landscape, season, and place.',
    signatureDishes: ['Pickled Herring & Dill', 'Wild Mushroom Broth', 'Sea Urchin Toast', 'Nordic Vegetables'],
    gradient: 'from-teal-600 to-cyan-500',
    stars: 2,
  },
  {
    id: 'ferran-adria',
    name: 'Ferran Adrià',
    title: 'Pioneer of Molecular Gastronomy',
    nationality: '🇪🇸 Spanish',
    category: 'michelin',
    cuisine: ['Avant-Garde', 'Catalan'],
    knownFor: 'elBulli, considered the world\'s best restaurant for years. Invented spherification, culinary foam, and deconstruction. Dishes like Liquid Olives and Parmesan Spaghetti.',
    philosophy: 'Creativity as an act of rebellion. Cuisine is not just food but art, emotion, and ideas.',
    signatureDishes: ['Spherified Olives', 'Gazpacho Deconstruction', 'Parmesan Spaghetti', 'Hot & Cold Beet'],
    gradient: 'from-yellow-500 to-orange-400',
    stars: 3,
  },
  {
    id: 'thomas-keller',
    name: 'Thomas Keller',
    title: '3-Michelin-Star Chef',
    nationality: '🇺🇸 American',
    category: 'michelin',
    cuisine: ['French-American', 'Fine Dining'],
    knownFor: 'The French Laundry in Napa Valley. Only American chef to hold 3 Michelin stars simultaneously at two restaurants. Known for Oysters & Pearls, Salmon Cornets, and exacting French technique.',
    philosophy: 'Respect for ingredients. Obsessive attention to detail. Consistency as the highest form of excellence.',
    signatureDishes: ['Oysters and Pearls', 'Salmon Tartare Cornet', 'Butter Poached Lobster', 'Pot de Crème'],
    gradient: 'from-amber-600 to-yellow-500',
    stars: 3,
  },
  {
    id: 'nobu-matsuhisa',
    name: 'Nobu Matsuhisa',
    title: 'Michelin-Starred Chef',
    nationality: '🇯🇵 Japanese',
    category: 'michelin',
    cuisine: ['Nobu-Style', 'Japanese-Peruvian'],
    knownFor: 'Nobu restaurants worldwide. Created Miso Cod (Black Cod with Miso), new-style sashimi with hot oil, and the Japanese-Peruvian fusion called Nikkei cuisine.',
    philosophy: 'Harmony of Japanese precision with South American boldness. Every dish must have balance of taste and texture.',
    signatureDishes: ['Black Cod with Miso', 'New Style Sashimi', 'Rock Shrimp Tempura', 'Yellowtail Jalapeño'],
    gradient: 'from-rose-600 to-pink-500',
    stars: 1,
  },
  {
    id: 'alain-ducasse',
    name: 'Alain Ducasse',
    title: '19-Michelin-Star Chef',
    nationality: '🇫🇷 French',
    category: 'michelin',
    cuisine: ['Haute Cuisine', 'Provençal'],
    knownFor: 'Most Michelin-starred chef in history. Restaurants in Paris, Monaco, London. Known for elaborate sauces, luxury ingredients, and the definitive French haute cuisine tradition.',
    philosophy: 'French cuisine is a living art. Luxury and simplicity are not opposites — they are the same philosophy executed at different scales.',
    signatureDishes: ['Sole Meunière', 'Poulet Rôti', 'Langoustine Ravioli', 'Mille-Feuille'],
    gradient: 'from-blue-700 to-indigo-600',
    stars: 19,
  },
  {
    id: 'eric-ripert',
    name: 'Eric Ripert',
    title: '3-Michelin-Star Chef',
    nationality: '🇫🇷 French',
    category: 'michelin',
    cuisine: ['French Seafood', 'Fine Dining'],
    knownFor: 'Le Bernardin in New York, consistently rated among world\'s best. The temple of French seafood cuisine in America. Famous for near-raw fish preparations and pristine French technique.',
    philosophy: 'Fish first. Every preparation must reveal the pure essence of the sea.',
    signatureDishes: ['Barely Cooked Salmon', 'Tuna Ribbons', 'Lobster Bisque', 'Layered Yellowfin Tuna'],
    gradient: 'from-sky-600 to-blue-500',
    stars: 3,
  },
  {
    id: 'jose-andres',
    name: 'José Andrés',
    title: 'Michelin-Starred Chef & Humanitarian',
    nationality: '🇪🇸 Spanish',
    category: 'michelin',
    cuisine: ['Spanish', 'Avant-Garde'],
    knownFor: 'Minibar in Washington DC, World Central Kitchen founder. Brought Spanish tapas culture to America. Famous for Gazpacho shots, Gin & Tonic spheres, and modernist Spanish classics.',
    philosophy: 'Food is a universal language. To feed people is the highest act of love.',
    signatureDishes: ['Modern Gazpacho', 'Iberian Ham with Tomato', 'Spanish Tortilla', 'Gin & Tonic Spheres'],
    gradient: 'from-red-700 to-rose-500',
    stars: 2,
  },
  {
    id: 'alice-waters',
    name: 'Alice Waters',
    title: 'Pioneer of Farm-to-Table',
    nationality: '🇺🇸 American',
    category: 'michelin',
    cuisine: ['Californian', 'French-inspired'],
    knownFor: 'Chez Panisse in Berkeley. Godmother of American food. Pioneered farm-to-table and organic cuisine before it was fashionable. Believed great ingredients need minimal intervention.',
    philosophy: 'The garden is the source. Simple food from perfect, local, organic ingredients is the highest cuisine.',
    signatureDishes: ['Garlic Soup', 'Grilled Whole Fish', 'Warm Salad of Duck Confit', 'Almond Tart'],
    gradient: 'from-lime-600 to-green-500',
  },
  {
    id: 'david-chang',
    name: 'David Chang',
    title: 'Michelin-Starred Chef',
    nationality: '🇺🇸 Korean-American',
    category: 'michelin',
    cuisine: ['Korean-American', 'Asian Fusion'],
    knownFor: 'Momofuku empire. Brought Korean flavors, gochujang, and bo ssäm to fine dining. Netflix Ugly Delicious. Known for pork buns, ramen, and fearlessly casual fine dining.',
    philosophy: 'Good food doesn\'t need white tablecloths. Bold Asian flavors deserve a seat at the fine dining table.',
    signatureDishes: ['Momofuku Pork Buns', 'Bo Ssäm', 'Momofuku Ramen', 'Kimchi Fried Rice'],
    gradient: 'from-orange-600 to-red-500',
    stars: 2,
  },
  {
    id: 'gaggan-anand',
    name: 'Gaggan Anand',
    title: 'Asia\'s Best Restaurant 2015-2018',
    nationality: '🇮🇳 Indian',
    category: 'michelin',
    cuisine: ['Progressive Indian', 'Molecular'],
    knownFor: 'Gaggan restaurant in Bangkok, 4× Asia\'s Best Restaurant. Reinvented Indian street food with molecular techniques. Famous for emoji menus, yogurt spheres, and lollipop lamb chops.',
    philosophy: 'Indian food is not just curry. It is 5000 years of civilization on a plate.',
    signatureDishes: ['Yogurt Sphere', 'Lollipop Lamb Chops', 'Charcoal Lamb Seekh', 'Eggplant Miso'],
    gradient: 'from-orange-500 to-amber-400',
  },
  {
    id: 'dominique-crenn',
    name: 'Dominique Crenn',
    title: '3-Michelin-Star Chef',
    nationality: '🇫🇷 French',
    category: 'michelin',
    cuisine: ['Poetic Culinaria', 'French'],
    knownFor: 'Atelier Crenn in San Francisco. First female chef in the US to receive 3 Michelin stars. Known for poetic cuisine — each dish inspired by a poem, using ingredients from her garden.',
    philosophy: 'Cuisine as poetry. Each dish is an emotional narrative, not just nourishment.',
    signatureDishes: ['Snow Egg', 'Garden Poem Salad', 'Uni Toast', 'Lamb with Herbs'],
    gradient: 'from-purple-600 to-violet-500',
    stars: 3,
  },
  {
    id: 'grant-achatz',
    name: 'Grant Achatz',
    title: '3-Michelin-Star Chef',
    nationality: '🇺🇸 American',
    category: 'michelin',
    cuisine: ['Molecular', 'Avant-Garde American'],
    knownFor: 'Alinea in Chicago, Next, Aviary. Overcame tongue cancer to cook. Known for edible helium balloons, tablecloth desserts, and eliminating traditional courses entirely.',
    philosophy: 'Deconstruct everything. Rebuild it in a way no one has imagined. Then do it differently next time.',
    signatureDishes: ['Edible Helium Balloon', 'Hot Potato Cold Potato', 'Truffle Explosion', 'Black Truffle Dish'],
    gradient: 'from-slate-700 to-gray-600',
    stars: 3,
  },
  {
    id: 'yotam-ottolenghi',
    name: 'Yotam Ottolenghi',
    title: 'Chef & Cookbook Author',
    nationality: '🇮🇱 Israeli-British',
    category: 'michelin',
    cuisine: ['Middle Eastern', 'Mediterranean', 'Vegetable-Forward'],
    knownFor: 'Ottolenghi delis in London. Author of Plenty, Jerusalem, Simple. Revolutionized vegetable cooking with bold Middle Eastern spices, tahini, pomegranate, and sumac.',
    philosophy: 'Vegetables deserve to be the star. Middle Eastern and Mediterranean flavors are the most vibrant on earth.',
    signatureDishes: ['Roasted Cauliflower with Tahini', 'Jerusalem Chicken', 'Shakshuka', 'Miso Aubergine'],
    gradient: 'from-yellow-600 to-lime-500',
  },
  {
    id: 'virgilio-martinez',
    name: 'Virgilio Martínez',
    title: 'Latin America\'s Best Chef',
    nationality: '🇵🇪 Peruvian',
    category: 'michelin',
    cuisine: ['Peruvian', 'Andean'],
    knownFor: 'Central restaurant in Lima, World\'s Best Restaurant 2023. Maps Peruvian cuisine by altitude — each course from a different ecosystem from the Amazon to the Andes.',
    philosophy: 'Peru is the most biodiverse country on earth. Every altitude, every ecosystem has its own flavor.',
    signatureDishes: ['Amazon River Trout', 'Ceviche Central Style', 'Andean Grains Bowl', 'Caramelized Chirimoya'],
    gradient: 'from-emerald-600 to-teal-500',
  },

  // ── TV CHEFS ──────────────────────────────────────────────────────────────
  {
    id: 'julia-child',
    name: 'Julia Child',
    title: 'The French Chef (1961-1989)',
    nationality: '🇺🇸 American',
    category: 'tv',
    cuisine: ['French', 'Classic American'],
    knownFor: 'The French Chef on PBS. Author of Mastering the Art of French Cooking. Brought French cuisine to American home cooks. Famous for Boeuf Bourguignon, Coq au Vin, and French omelettes.',
    philosophy: 'Cooking is not a chore. It is one of life\'s great pleasures. Don\'t be afraid. Bon appétit!',
    signatureDishes: ['Boeuf Bourguignon', 'Coq au Vin', 'French Omelette', 'Vichyssoise'],
    gradient: 'from-blue-500 to-indigo-400',
  },
  {
    id: 'anthony-bourdain',
    name: 'Anthony Bourdain',
    title: 'Chef, Author & TV Host',
    nationality: '🇺🇸 American',
    category: 'tv',
    cuisine: ['French Brasserie', 'Street Food'],
    knownFor: 'Kitchen Confidential, Parts Unknown on CNN. Worked Les Halles in New York. Championed street food and anti-pretension in dining. Famous for steak frites, simple French classics, and world street food.',
    philosophy: 'The best meal is always the one you didn\'t expect, eaten with strangers who become friends.',
    signatureDishes: ['Steak Frites', 'Roast Bone Marrow', 'Vietnamese Pho', 'Simple Roast Chicken'],
    gradient: 'from-zinc-700 to-stone-600',
  },
  {
    id: 'bobby-flay',
    name: 'Bobby Flay',
    title: 'Iron Chef & TV Host',
    nationality: '🇺🇸 American',
    category: 'tv',
    cuisine: ['Southwestern', 'American BBQ'],
    knownFor: 'Iron Chef, Beat Bobby Flay, Throwdown. Famous for Southwestern flavors — chipotle, ancho chili, blue corn, mesa grills. Known for bold spice rubs, grilling, and challenge cooking.',
    philosophy: 'Big, bold flavors. The grill is not just a cooking tool, it\'s a way of life.',
    signatureDishes: ['Green Chile Cheeseburger', 'Shrimp & Grits', 'BBQ Chicken Mesa Style', 'Blue Corn Pancakes'],
    gradient: 'from-red-500 to-orange-400',
  },
  {
    id: 'ina-garten',
    name: 'Ina Garten',
    title: 'The Barefoot Contessa',
    nationality: '🇺🇸 American',
    category: 'tv',
    cuisine: ['French-inspired American', 'Comfort Food'],
    knownFor: 'Barefoot Contessa on Food Network. Beloved for approachable, elegant entertaining food. Famous for roast chicken, Parker\'s beef stew, lemon cake, and the advice "use good vanilla."',
    philosophy: 'Good food for friends and family doesn\'t need to be complicated. Buy the best ingredients and get out of the way.',
    signatureDishes: ['Perfect Roast Chicken', 'Parker\'s Beef Stew', 'Lemon Cake', 'Baked Mac and Cheese'],
    gradient: 'from-amber-500 to-yellow-400',
  },
  {
    id: 'nigella-lawson',
    name: 'Nigella Lawson',
    title: 'Domestic Goddess',
    nationality: '🇬🇧 British',
    category: 'tv',
    cuisine: ['British Comfort', 'Indulgent Baking'],
    knownFor: 'Nigella Bites, Nigella Lawson: Simply Nigella. The queen of indulgent comfort food. Famous for midnight fridge raids, Chocolate Guinness Cake, and making cooking feel joyful and sensual.',
    philosophy: 'Food is comfort, pleasure, and love. Cooking should never feel like a duty.',
    signatureDishes: ['Chocolate Guinness Cake', 'Butter Chicken', 'Salted Caramel Chocolate Tart', 'Banana Bread'],
    gradient: 'from-pink-600 to-rose-500',
  },
  {
    id: 'guy-fieri',
    name: 'Guy Fieri',
    title: 'Mayor of Flavortown',
    nationality: '🇺🇸 American',
    category: 'tv',
    cuisine: ['American Diner', 'BBQ', 'Street Food'],
    knownFor: 'Diners, Drive-Ins and Dives on Food Network. The face of American comfort food. Famous for garbage plates, loaded burgers, smoked meats, and the philosophy "Winner Winner Chicken Dinner."',
    philosophy: 'Real food for real people. The best restaurants are the ones nobody knows about yet.',
    signatureDishes: ['Trash Can Nachos', 'Triple D Burger', 'Smoked Pulled Pork', 'Donkey Sauce Burger'],
    gradient: 'from-yellow-400 to-red-400',
  },
  {
    id: 'mary-berry',
    name: 'Mary Berry',
    title: 'Queen of British Baking',
    nationality: '🇬🇧 British',
    category: 'tv',
    cuisine: ['British Baking', 'Traditional'],
    knownFor: 'Great British Bake Off judge. 70+ cookbooks. The authority on British baking. Famous for Victoria Sponge, Moist Chocolate Cake, and no-nonsense practical baking that always works.',
    philosophy: 'Baking is love made edible. A good recipe should always work the first time.',
    signatureDishes: ['Victoria Sponge', 'Chocolate Traybake', 'Lemon Drizzle Cake', 'Classic Scones'],
    gradient: 'from-pink-400 to-purple-400',
  },
  {
    id: 'rick-stein',
    name: 'Rick Stein',
    title: 'Seafood & Travel Chef',
    nationality: '🇬🇧 British',
    category: 'tv',
    cuisine: ['British Seafood', 'Global Coastal'],
    knownFor: 'The Seafood Restaurant in Padstow. Rick Stein\'s Seafood, Far Eastern Odyssey, From Venice to Istanbul. The definitive British seafood chef with a love of global coastal cuisines.',
    philosophy: 'The sea is the world\'s greatest pantry. Freshness and simplicity are everything.',
    signatureDishes: ['Fish & Chips', 'Fruits de Mer', 'Grilled Whole Sea Bass', 'Moules Marinières'],
    gradient: 'from-blue-600 to-cyan-500',
  },
  {
    id: 'emeril-lagasse',
    name: 'Emeril Lagasse',
    title: 'BAM! Chef',
    nationality: '🇺🇸 American',
    category: 'tv',
    cuisine: ['Creole', 'New Orleans', 'American'],
    knownFor: 'Essence of Emeril, Emeril Live. The chef who "kicked it up a notch." Champion of New Orleans Creole and Cajun cuisine. Famous for Creole jambalaya, étouffée, and explosive seasoning.',
    philosophy: 'Cooking is about kicking up the flavor. BAM! Life is too short for bland food.',
    signatureDishes: ['New Orleans BBQ Shrimp', 'Creole Jambalaya', 'Crawfish Étouffée', 'Bananas Foster'],
    gradient: 'from-green-600 to-lime-500',
  },
  {
    id: 'alton-brown',
    name: 'Alton Brown',
    title: 'The Science of Cooking',
    nationality: '🇺🇸 American',
    category: 'tv',
    cuisine: ['Scientific American', 'Food Science'],
    knownFor: 'Good Eats on Food Network. The food scientist of TV. Explains the chemistry and physics behind cooking. Believes every cook should understand why, not just how.',
    philosophy: 'Understanding the science of cooking makes you a better cook. Every technique has a reason.',
    signatureDishes: ['Perfect Brined Turkey', 'Overnight Oats', 'Cast Iron Steak', 'Overnight Cinnamon Rolls'],
    gradient: 'from-indigo-600 to-blue-500',
  },
  {
    id: 'vikas-khanna',
    name: 'Vikas Khanna',
    title: 'Michelin-Starred Indian Chef',
    nationality: '🇮🇳 Indian',
    category: 'tv',
    cuisine: ['Contemporary Indian', 'Kashmiri'],
    knownFor: 'Junoon restaurant in NYC, Michelin star. MasterChef India judge. Ambassador of Indian cuisine to the world. Known for refined Indian recipes and humanitarian work feeding millions.',
    philosophy: 'Indian cuisine is the world\'s oldest and most diverse. My job is to show its full glory.',
    signatureDishes: ['Butter Chicken', 'Rogan Josh', 'Dal Makhani', 'Kashmiri Wazwan'],
    gradient: 'from-orange-500 to-red-400',
    stars: 1,
  },
  {
    id: 'sanjeev-kapoor',
    name: 'Sanjeev Kapoor',
    title: 'India\'s Most Celebrated Chef',
    nationality: '🇮🇳 Indian',
    category: 'tv',
    cuisine: ['Indian', 'Regional Indian'],
    knownFor: 'Khana Khazana — longest running cooking show in Asia. Over 200 cookbooks. Built the first dedicated food channel (Food Food) in India. Made Indian home cooking accessible to millions.',
    philosophy: 'Food is the greatest equalizer. Every Indian home can cook restaurant-quality food.',
    signatureDishes: ['Chicken Tikka Masala', 'Shahi Paneer', 'Makhani Dal', 'Gajar ka Halwa'],
    gradient: 'from-amber-600 to-orange-500',
  },

  // ── CREATORS / INFLUENCERS ────────────────────────────────────────────────
  {
    id: 'joshua-weissman',
    name: 'Joshua Weissman',
    title: 'But Better YouTube Chef',
    nationality: '🇺🇸 American',
    category: 'creator',
    cuisine: ['American', 'Homemade Fast Food'],
    knownFor: '10M+ YouTube subscribers. "But Better" series recreating fast food and restaurant dishes at home. Known for extreme technique on budget, homemade Big Mac, Chick-fil-A, and sourdough.',
    philosophy: 'Anyone can make better food at home than any fast food chain. Don\'t settle for less.',
    signatureDishes: ['Homemade Big Mac', 'Better Than Chick-fil-A Sandwich', 'Sourdough Bread', 'Smash Burger'],
    gradient: 'from-yellow-500 to-orange-400',
    handle: '@JoshuaWeissman',
  },
  {
    id: 'babish',
    name: 'Andrew Rea (Babish)',
    title: 'Binging with Babish',
    nationality: '🇺🇸 American',
    category: 'creator',
    cuisine: ['Pop Culture Food', 'American'],
    knownFor: '10M+ YouTube. Recreates food from movies, TV shows, and pop culture. Started with the Moistmaker from Friends. Known for Krabby Patty, Ratatouille\'s Ratatouille, and precise technique.',
    philosophy: 'Food from fiction can be real and delicious. Cooking is a way to connect with stories we love.',
    signatureDishes: ['The Moistmaker Sandwich', 'Krabby Patty Burger', 'Ratatouille Confit Byaldi', 'Steamed Hams'],
    gradient: 'from-gray-700 to-zinc-600',
    handle: '@bingingwithbabish',
  },
  {
    id: 'ethan-chlebowski',
    name: 'Ethan Chlebowski',
    title: 'Evidence-Based Cooking',
    nationality: '🇺🇸 American',
    category: 'creator',
    cuisine: ['Healthy', 'Evidence-Based'],
    knownFor: '3M+ YouTube. Science-based approach to cooking and nutrition. Rigorously tests every claim. Known for better pasta, healthier weight-loss cooking, and debunking food myths.',
    philosophy: 'Trust the science, test the recipe. Better food through evidence, not tradition.',
    signatureDishes: ['High-Protein Pasta', 'Perfect Scrambled Eggs', 'Better Bolognese', 'Crispy Smash Burger'],
    gradient: 'from-blue-500 to-cyan-400',
    handle: '@EthanChlebowski',
  },
  {
    id: 'salt-bae',
    name: 'Nusret Gökçe (Salt Bae)',
    title: 'World\'s Most Famous Butcher',
    nationality: '🇹🇷 Turkish',
    category: 'creator',
    cuisine: ['Ottoman Steakhouse', 'Turkish BBQ'],
    knownFor: 'Nusr-Et steakhouse chain worldwide. The viral salt sprinkling meme. Known for theatrical Ottoman-style meat preparation, gold-wrapped steaks, extreme tomahawks, and his signature salt toss.',
    philosophy: 'Meat is an art. The cut, the seasoning, the presentation — every movement is performance.',
    signatureDishes: ['Ottoman Steak', 'Gold Tomahawk', 'Smash Burger Turkish Style', 'Kebab Nusr-Et'],
    gradient: 'from-amber-500 to-yellow-400',
    handle: '@nusr_et',
  },
  {
    id: 'claire-saffitz',
    name: 'Claire Saffitz',
    title: 'Pastry Chef & YouTube Creator',
    nationality: '🇺🇸 American',
    category: 'creator',
    cuisine: ['Pastry', 'French Technique', 'Baking'],
    knownFor: 'Bon Appétit\'s "Gourmet Makes" series. Making Gushers, Peeps, and Oreos from scratch. Author of Dessert Person. Known for meticulous French pastry technique and obsessive recipe development.',
    philosophy: 'Baking is precise but never rigid. Understanding the why gives you the freedom to improvise.',
    signatureDishes: ['Croissants', 'Gourmet Gushers', 'Cream Puffs', 'Caramelized Onion Tart'],
    gradient: 'from-rose-500 to-pink-400',
    handle: '@csaffitz',
  },
  {
    id: 'kenji-lopez-alt',
    name: 'J. Kenji López-Alt',
    title: 'The Food Lab',
    nationality: '🇺🇸 American',
    category: 'creator',
    cuisine: ['American', 'Scientific Method'],
    knownFor: 'The Food Lab cookbook, Serious Eats Managing Editor. Tests every cooking variable scientifically. Perfected smash burgers, reverse-sear steak, wok technique, and why you should rest your meat.',
    philosophy: 'Every recipe should have a reason. Test 50 methods, keep one. Never trust assumptions about cooking.',
    signatureDishes: ['Smash Burger', 'Reverse Sear Steak', 'Wok-Fried Noodles', 'Perfect Roast Potatoes'],
    gradient: 'from-stone-600 to-amber-600',
    handle: '@kenjilopezalt',
  },
  {
    id: 'samin-nosrat',
    name: 'Samin Nosrat',
    title: 'Salt Fat Acid Heat',
    nationality: '🇮🇷 Iranian-American',
    category: 'creator',
    cuisine: ['Italian', 'Persian', 'Intuitive Cooking'],
    knownFor: 'Salt Fat Acid Heat on Netflix and book. Learned to cook at Chez Panisse under Alice Waters. Teaches cooking through 4 fundamental elements. Approachable, warm, and profoundly practical.',
    philosophy: 'Master salt, fat, acid, and heat and you can cook anything. Rules are for learners; intuition is for cooks.',
    signatureDishes: ['Buttermilk Chicken', 'Caramelized Onion Pasta', 'Persian Rice', 'Italian Salsa Verde'],
    gradient: 'from-orange-400 to-yellow-400',
    handle: '@saminnosrat',
  },
  {
    id: 'nick-digiovanni',
    name: 'Nick DiGiovanni',
    title: 'MasterChef Finalist & Creator',
    nationality: '🇺🇸 American',
    category: 'creator',
    cuisine: ['American', 'Gourmet Elevated'],
    knownFor: 'MasterChef Season 10 runner-up. YouTube and Instagram creator. Known for world records (largest burger, pasta, etc.), Osmo Salt brand, and making fine dining accessible.',
    philosophy: 'Great food doesn\'t need a fancy restaurant. You can break records in your own kitchen.',
    signatureDishes: ['Black Truffle Pasta', 'Giant Beef Wellington', 'Perfect Wagyu Steak', 'Lobster Roll'],
    gradient: 'from-violet-600 to-purple-500',
    handle: '@nick.digiovanni',
  },
  {
    id: 'guga-foods',
    name: 'Gustavo Tosta (Guga)',
    title: 'Steak & Experiment YouTube Chef',
    nationality: '🇧🇷 Brazilian',
    category: 'creator',
    cuisine: ['Brazilian BBQ', 'Steak'],
    knownFor: 'Guga Foods YouTube (4M+). Experiments with steaks — 1-year dry aged, A5 Wagyu vs supermarket beef, gold-covered steaks, sous vide everything. Brazilian BBQ master.',
    philosophy: 'Every steak experiment teaches you something. The best meal is the one you made yourself.',
    signatureDishes: ['Dry-Aged Ribeye', 'Brazilian Picanha', 'Sous Vide Wagyu', 'Reverse Sear Tomahawk'],
    gradient: 'from-red-600 to-orange-600',
    handle: '@GugaFoods',
  },
  {
    id: 'adam-ragusea',
    name: 'Adam Ragusea',
    title: 'Food Journalist & Home Cook',
    nationality: '🇺🇸 American',
    category: 'creator',
    cuisine: ['American Home Cooking', 'Italian-American'],
    knownFor: '3M+ YouTube. Food journalist turned chef. Controversially champions home cook adaptations of classic recipes. Known for better pizza, pasta, and his anti-recipe-complexity stance.',
    philosophy: 'Perfect is the enemy of good. A home cook\'s job is to make delicious food, not to impress professionals.',
    signatureDishes: ['Home Cook Pizza', 'Better Spaghetti & Meatballs', 'Pan Steak with Basting', 'French Onion Soup'],
    gradient: 'from-teal-600 to-green-500',
    handle: '@aragusea',
  },
  {
    id: 'internet-shaquille',
    name: 'Internet Shaquille',
    title: 'The People\'s Chef',
    nationality: '🇺🇸 American',
    category: 'creator',
    cuisine: ['American', 'Budget Cooking'],
    knownFor: '2M+ YouTube. Makes incredible food on tight budgets. Challenges the notion that good cooking requires expensive ingredients. Warm, accessible teaching style.',
    philosophy: 'Great food is for everyone, not just those who can afford expensive ingredients.',
    signatureDishes: ['Budget Chicken Thighs', 'One-Pan Rice Dish', 'Cheap & Delicious Pasta', 'Pantry Stew'],
    gradient: 'from-green-500 to-emerald-400',
    handle: '@internetshaquille',
  },
  {
    id: 'maangchi',
    name: 'Maangchi',
    title: 'Queen of Korean Cooking',
    nationality: '🇰🇷 Korean',
    category: 'creator',
    cuisine: ['Korean', 'Traditional Korean'],
    knownFor: '7M+ YouTube. The most popular Korean cooking channel in the world. Authentic Korean home cooking — kimchi, bibimbap, tteokbokki, Korean fried chicken. Called "the Julia Child of Korea."',
    philosophy: 'Korean food is a love language. Every dish carries the warmth of home and mother.',
    signatureDishes: ['Kimchi Jjigae', 'Bibimbap', 'Korean Fried Chicken', 'Tteokbokki'],
    gradient: 'from-red-500 to-pink-400',
    handle: '@Maangchi',
  },
  {
    id: 'ranveer-brar',
    name: 'Ranveer Brar',
    title: 'Indian Chef & TV Host',
    nationality: '🇮🇳 Indian',
    category: 'creator',
    cuisine: ['Indian', 'Awadhi', 'Street Food'],
    knownFor: 'MasterChef India judge. Executive Chef at Boston restaurants. YouTube creator with 9M+ subscribers. Known for authentic Awadhi cuisine, street food storytelling, and ingredient history.',
    philosophy: 'Every Indian ingredient has a story of a thousand years. My cooking is storytelling.',
    signatureDishes: ['Galouti Kebab', 'Biryani Awadhi Style', 'Nihari', 'Kulfi Falooda'],
    gradient: 'from-orange-600 to-amber-500',
    handle: '@RanveerBrar',
  },
  {
    id: 'tasty-producer',
    name: 'Rie McClenny (Tasty)',
    title: 'Tasty Producer & Creator',
    nationality: '🇯🇵 Japanese',
    category: 'creator',
    cuisine: ['Japanese', 'Fusion', 'American'],
    knownFor: 'BuzzFeed Tasty producer. "Make It Fancy" series making cheap food look expensive. Known for Japanese-American fusion, ramen upgrades, and democratizing fancy cooking.',
    philosophy: 'Any cheap ingredient can be made beautiful. Fancy food is about technique, not price.',
    signatureDishes: ['Ramen Upgrade', 'Japanese Milk Bread', 'Matcha Cheesecake', 'Fancy Instant Ramen'],
    gradient: 'from-pink-500 to-rose-400',
    handle: '@riepechan',
  },

  // ── REGIONAL / WORLD ──────────────────────────────────────────────────────
  {
    id: 'marco-pierre-white',
    name: 'Marco Pierre White',
    title: 'First British 3-Michelin-Star Chef',
    nationality: '🇬🇧 British',
    category: 'regional',
    cuisine: ['British', 'French Classical'],
    knownFor: 'First British chef to earn 3 Michelin stars (age 33). Mentored Ramsay, Blumenthal, Curtis Stone. Returned all his stars saying "I was too young." Known for Harvey\'s classics and intense French technique.',
    philosophy: 'Nature is the true artist. A chef\'s job is not to interfere with what nature has already perfected.',
    signatureDishes: ['Tagliolini of Lobster', 'Braised Oxtail', 'Pan-Fried Sea Bass', 'Risotto of Woodland Mushrooms'],
    gradient: 'from-stone-700 to-zinc-600',
    stars: 3,
  },
  {
    id: 'magnus-nilsson',
    name: 'Magnus Nilsson',
    title: 'New Nordic Pioneer',
    nationality: '🇸🇪 Swedish',
    category: 'regional',
    cuisine: ['New Nordic', 'Swedish'],
    knownFor: 'Fäviken restaurant in remote Sweden (closed 2019). James Beard Award winner. Each dish used only what grew or lived within walking distance of the restaurant. Dried, fermented, and cured.',
    philosophy: 'Food from the land around you is all you need. Locality is not a trend — it is the only honest way to cook.',
    signatureDishes: ['Scallop Cooked Over Juniper', 'Raw Langoustine', 'Dried Reindeer Heart', 'Aged Milk Crust'],
    gradient: 'from-slate-600 to-blue-600',
  },
  {
    id: 'nadia-santini',
    name: 'Nadia Santini',
    title: 'Best Female Chef in the World 2013',
    nationality: '🇮🇹 Italian',
    category: 'regional',
    cuisine: ['Mantovan Italian', 'Northern Italian'],
    knownFor: 'Dal Pescatore in Mantova, 3 Michelin stars. World\'s Best Female Chef 2013. Cooks the cuisine of Mantova — tortelli with pumpkin and amaretti, risotto, river fish, and centuries-old Northern Italian recipes.',
    philosophy: 'I cook the land. The Po Valley, the river, the seasons — that is my menu.',
    signatureDishes: ['Tortelli di Zucca', 'Risotto alla Pilota', 'River Pike Terrine', 'Agnoli in Broth'],
    gradient: 'from-green-700 to-emerald-600',
    stars: 3,
  },
  {
    id: 'madhur-jaffrey',
    name: 'Madhur Jaffrey',
    title: 'Queen of Indian Cooking',
    nationality: '🇮🇳 Indian-British',
    category: 'regional',
    cuisine: ['Indian', 'Regional Indian'],
    knownFor: 'An Invitation to Indian Cooking (1973). The person who introduced authentic Indian cooking to the West. Actress turned chef. Showed that Indian cuisine is not "curry powder" but a vast and nuanced tradition.',
    philosophy: 'Indian food is not one thing. It is a continent of flavors — 29 states, 1000 languages, infinite recipes.',
    signatureDishes: ['Rogan Josh', 'Lamb Korma', 'Spiced Chickpeas', 'Rice Pudding Kheer'],
    gradient: 'from-amber-600 to-red-500',
  },
  {
    id: 'ana-ros',
    name: 'Ana Roš',
    title: 'World\'s Best Female Chef 2017',
    nationality: '🇸🇮 Slovenian',
    category: 'regional',
    cuisine: ['Slovenian', 'Alpine'],
    knownFor: 'Hiša Franko in Kobarid, Slovenia. Taught herself to cook, no formal training. Uses Alpine ingredients — trout, deer, foraged herbs, local dairy. Put Slovenian cuisine on the global map.',
    philosophy: 'I cook what grows in my valley. The mountains, the river, the forest — they are my cookbook.',
    signatureDishes: ['Soča Trout', 'Venison with Juniper', 'Alpine Cheese Fondue', 'Buckwheat Žganci'],
    gradient: 'from-teal-700 to-green-600',
  },
  {
    id: 'yoshihiro-narisawa',
    name: 'Yoshihiro Narisawa',
    title: 'Innovative Satoyama Cuisine',
    nationality: '🇯🇵 Japanese',
    category: 'regional',
    cuisine: ['Japanese', 'French-Japanese', 'Satoyama'],
    knownFor: 'Narisawa in Tokyo, Asia\'s Best Restaurant multiple times. Created "Satoyama Cuisine" — cooking inspired by the space between mountains and civilisation. Bread baked at the table, forest on a plate.',
    philosophy: 'Nature is the chef. I am just her interpreter. Every dish must respect the ecosystem.',
    signatureDishes: ['Bread of the Forest', 'Satoyama Scenery', 'Charcoal-Grilled Duck', 'Living Forest Soup'],
    gradient: 'from-green-800 to-teal-700',
  },
  {
    id: 'paul-bocuse',
    name: 'Paul Bocuse',
    title: 'The Pope of French Cuisine',
    nationality: '🇫🇷 French',
    category: 'regional',
    cuisine: ['Nouvelle Cuisine', 'Lyonnais'],
    knownFor: 'L\'Auberge du Pont de Collonges. Held 3 Michelin stars for 55 consecutive years. Founded Nouvelle Cuisine — lighter, ingredient-forward French cooking. The most influential French chef of the 20th century.',
    philosophy: 'French cuisine is the mother of all cuisines. Respect the ingredient, master the technique, and cook with your heart.',
    signatureDishes: ['Truffle Soup VGE', 'Sea Bass in Pastry', 'Bresse Chicken en Demi-Deuil', 'Loup en Croûte'],
    gradient: 'from-blue-800 to-indigo-700',
    stars: 3,
  },
];

export function searchChefs(query: string, category?: ChefCategory): Chef[] {
  const q = query.toLowerCase();
  return CHEFS.filter(chef => {
    const matchesSearch = !q ||
      chef.name.toLowerCase().includes(q) ||
      chef.cuisine.some(c => c.toLowerCase().includes(q)) ||
      chef.nationality.toLowerCase().includes(q) ||
      chef.knownFor.toLowerCase().includes(q);
    const matchesCategory = !category || chef.category === category;
    return matchesSearch && matchesCategory;
  });
}
